/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Entidades.*;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Jimmy
 */
public class frmHospital extends javax.swing.JFrame {

    /**
     * Creates new form frmHospital
     */
            
    ArrayList<Doctor> listadoDoctores;
    DefaultTableModel modeloDoctor;
    DefaultTableModel modeloPaciente;
    DefaultTableModel modeloPacienteVacio; 
    
    public frmHospital() {
        initComponents();
        
        listadoDoctores = new ArrayList<>();
        modeloDoctor = (DefaultTableModel) this.jtDoctor.getModel();
        modeloPaciente = (DefaultTableModel) this.jtPaciente.getModel(); 
        
        this.btnBuscarDoctor.setEnabled(false);
        this.btnTotalizar.setEnabled(false);
        this.btnRecargar.setEnabled(false);
        
        this.cbEstado.addItem("Leve");
        this.cbEstado.addItem("Moderado");
        this.cbEstado.addItem("Grave");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnTotalizar = new javax.swing.JButton();
        btnBuscarDoctor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarDoctor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPaciente = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDoctor = new javax.swing.JTable();
        cbEstado = new javax.swing.JComboBox<>();
        lblNumPacientes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCargarDatos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnRecargar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCantidadPacientes = new javax.swing.JTextField();
        txtCantidadDoctores = new javax.swing.JTextField();
        btnAdministrarDatos = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnDetallesPacientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Totalizar por estado del paciente:");

        btnTotalizar.setText("Totalizar");
        btnTotalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalizarActionPerformed(evt);
            }
        });

        btnBuscarDoctor.setText("Buscar");
        btnBuscarDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDoctorActionPerformed(evt);
            }
        });

        jLabel6.setText("Buscar Doctor por ID:");

        jLabel1.setText("Doctores:");

        jLabel2.setText("Pacientes:");

        jtPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Padecimiento", "Estado", "Fecha de ingreso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPaciente.setName("jtPaciente"); // NOI18N
        jScrollPane1.setViewportView(jtPaciente);

        jtDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Especialidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtDoctor.setName(""); // NOI18N
        jtDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDoctorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtDoctor);

        lblNumPacientes.setText("Pacientes");

        jLabel3.setText("Generar datos:");

        btnCargarDatos.setText("Generar");
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        jLabel7.setText("Recargar tablas:");

        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad doctores:");

        jLabel8.setText("Cantidad pacientes:");

        btnAdministrarDatos.setText("Administrar datos");
        btnAdministrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarDatosActionPerformed(evt);
            }
        });

        jLabel10.setText("Procesar de la máquina:");

        jLabel11.setText("Sistema operativo:");

        btnDetallesPacientes.setText("Detalles de los pacientes");
        btnDetallesPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesPacientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidadDoctores)
                            .addComponent(txtCantidadPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTotalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarDoctor))
                            .addComponent(lblNumPacientes)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRecargar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDetallesPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdministrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCantidadDoctores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCantidadPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnCargarDatos))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarDoctor)
                            .addComponent(txtBuscarDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTotalizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNumPacientes)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(btnRecargar))
                        .addGap(18, 18, 18)
                        .addComponent(btnAdministrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDetallesPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDoctorActionPerformed
        //TODO add your handling code here:
        this.modeloDoctor.getDataVector().removeAllElements();
        this.modeloPaciente.setRowCount(0);
        
        String busquedaDoctor = this.txtBuscarDoctor.getText().toUpperCase();
        
        for (int i = 0; i < this.listadoDoctores.size(); i++){
            if(busquedaDoctor.equals(listadoDoctores.get(i).ID.toUpperCase())){
                String[] registroDoctores = {
                    this.listadoDoctores.get(i).ID, 
                    this.listadoDoctores.get(i).nombre, 
                    this.listadoDoctores.get(i).especialidad
                };
                modeloDoctor.addRow(registroDoctores);
            }            
        }
    }//GEN-LAST:event_btnBuscarDoctorActionPerformed

    private void btnTotalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalizarActionPerformed
        // TODO add your handling code here:
        int contadorPacientes = 0;
        String opcionSeleccionada = this.cbEstado.getSelectedItem().toString();
        
        for(int i = 0; i < this.listadoDoctores.size(); i++){
            for(int j = 0; j < this.listadoDoctores.get(i).listaPacientes.size(); j++){
                if(opcionSeleccionada.equals(this.listadoDoctores.get(i).listaPacientes.get(j).estado)){
                    contadorPacientes++;
                }
            }
        }
        
        lblNumPacientes.setText("Número de pacientes en estado " + opcionSeleccionada.toLowerCase() + ": " + contadorPacientes);
    }//GEN-LAST:event_btnTotalizarActionPerformed

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
        // TODO add your handling code here:
        int cantidadDoctores = Integer.parseInt(txtCantidadDoctores.getText());
        int cantidadPacientes = Integer.parseInt(txtCantidadPacientes.getText());
    }//GEN-LAST:event_btnCargarDatosActionPerformed

    private void jtDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDoctorMouseClicked
        // TODO add your handling code here:
        int indiceDoctor = this.jtDoctor.getSelectedRow();
        int cantidadPacientes = this.listadoDoctores.get(indiceDoctor).listaPacientes.size();
        modeloPaciente.getDataVector().removeAllElements();
        
        for(int i = 0; i<cantidadPacientes; i++){
            String [] registroPacientes = {
                this.listadoDoctores.get(indiceDoctor).listaPacientes.get(i).ID, 
                this.listadoDoctores.get(indiceDoctor).listaPacientes.get(i).nombre,            
                this.listadoDoctores.get(indiceDoctor).listaPacientes.get(i).padecimiento, 
                this.listadoDoctores.get(indiceDoctor).listaPacientes.get(i).estado
            };
            modeloPaciente.addRow(registroPacientes);
        }
    }//GEN-LAST:event_jtDoctorMouseClicked

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        // TODO add your handling code here:
        this.modeloDoctor.getDataVector().removeAllElements();
        this.modeloPaciente.setRowCount(0);
        
        for(int i=0; i<this.listadoDoctores.size(); i++)
        {
            String[] registroDoctores = {
                this.listadoDoctores.get(i).ID, 
                this.listadoDoctores.get(i).nombre, 
                this.listadoDoctores.get(i).especialidad
            };
            modeloDoctor.addRow(registroDoctores);
        }
        
        txtBuscarDoctor.setText("");
    }//GEN-LAST:event_btnRecargarActionPerformed

 
    private void btnAdministrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarDatosActionPerformed
        // TODO add your handling code here:
        frmAdministrar formAdministrar = new frmAdministrar();
        formAdministrar.setVisible(true);
    }//GEN-LAST:event_btnAdministrarDatosActionPerformed

    private void btnDetallesPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesPacientesActionPerformed
        // TODO add your handling code here:
        frmDetalles formDetalles = new frmDetalles();
        formDetalles.setVisible(true);
    }//GEN-LAST:event_btnDetallesPacientesActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarDatos;
    private javax.swing.JButton btnBuscarDoctor;
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnDetallesPacientes;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton btnTotalizar;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtDoctor;
    private javax.swing.JTable jtPaciente;
    private javax.swing.JLabel lblNumPacientes;
    private javax.swing.JTextField txtBuscarDoctor;
    private javax.swing.JTextField txtCantidadDoctores;
    private javax.swing.JTextField txtCantidadPacientes;
    // End of variables declaration//GEN-END:variables
}
